# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitty" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "982e9745fe282e33491dc0a0045c993f69c051f81ed81cabd9ba1f926c02e3b0"
      url "https://github.com/wiremeusd/gitty/releases/download/v#{version}/gitty_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d21bc720d6b828c567544f8f3a7fbf06ff8744af1d2d632bc6489e05967c16ac"
      url "https://github.com/wiremeusd/gitty/releases/download/v#{version}/gitty_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "48a86703a8722900c2dcfbb43d121d2b9c0b42603f7d9ecc39a57233bc7f006a"
      url "https://github.com/wiremeusd/gitty/releases/download/v#{version}/gitty_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a1eab9fd7a9d26eebd833b771f286a1815897804fd7f84efc6c89056c27e4c2c"
      url "https://github.com/wiremeusd/gitty/releases/download/v#{version}/gitty_linux_arm64.tar.gz"
    end
  end

  name "gitty"
  desc "Interactive GitHub repo cloning from the terminal"
  homepage "https://gitty.pro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitty"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitty"]
    end
  end

  # No zap stanza required

end
