# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitty" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "24dcebc418476a5b346c6f0e0cf715865f8e6d2c51fb812ec77b767f21dc1ad5"
      url "https://github.com/wiremeusd/gitty/releases/download/v#{version}/gitty_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "54388a871a449801c683b7593f9bee6450bc9db9e0d4469bb28c70f49a62a9cd"
      url "https://github.com/wiremeusd/gitty/releases/download/v#{version}/gitty_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a139afeb3ee5a8ecb807183ead6e5185378888060f9a23143f08634e296dff18"
      url "https://github.com/wiremeusd/gitty/releases/download/v#{version}/gitty_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2adc2d24dd175d724a0ab7223edbea1e021ef8a0d635e0ef8ab5fc15e0165c8c"
      url "https://github.com/wiremeusd/gitty/releases/download/v#{version}/gitty_linux_arm64.tar.gz"
    end
  end

  name "gitty"
  desc "Interactive GitHub repo cloning from the terminal"
  homepage "https://github.com/wiremeusd/gitty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitty"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitty"]
    end
  end

  # No zap stanza required

end
