# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitty" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "17c7a2e70a80628f4efa6ff6db0958ce0ef5802e7be0a17c6c3dfa27af8bb549"
      url "https://github.com/wiremeusd/gitty/releases/download/v#{version}/gitty_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "656269f433d138d07643d38761ad9d8be8107e6bee536f220c3276c91b55222c"
      url "https://github.com/wiremeusd/gitty/releases/download/v#{version}/gitty_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2098a0140e6b1d005242b17031d302b14e284b638bc0f70946f2bcfe403cd4d4"
      url "https://github.com/wiremeusd/gitty/releases/download/v#{version}/gitty_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "92264325fd0ee00b8b4bc61336fd8e791d8a29d0047e91e8c882e6f6927442f5"
      url "https://github.com/wiremeusd/gitty/releases/download/v#{version}/gitty_linux_arm64.tar.gz"
    end
  end

  name "gitty"
  desc "Interactive GitHub repo cloning from the terminal"
  homepage "https://github.com/wiremeusd/gitty"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitty"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gitty"]
    end
  end

  # No zap stanza required

end
