# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitty < Formula
  desc "Interactive GitHub repo cloning from the terminal"
  homepage "https://github.com/wiremeusd/gitty"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/wiremeusd/gitty/releases/download/v0.1.0/gitty_0.1.0_darwin_amd64.tar.gz"
    sha256 "2a57430286373bc5a08a7937be985767aac74d61ca96cf1c474a7c6d5630ccad"

    define_method(:install) do
      bin.install "gitty"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/wiremeusd/gitty/releases/download/v0.1.0/gitty_0.1.0_darwin_arm64.tar.gz"
    sha256 "49c6931a85ff0cb9f8596823b8f82483129253a657b7643d1bd9f2369cace6e0"

    define_method(:install) do
      bin.install "gitty"
    end
  end

  test do
    system "#{bin}/gitty --version"
  end
end
