# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitty < Formula
  desc "Interactive GitHub repo cloning from the terminal"
  homepage "https://github.com/wiremeusd/gitty"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/wiremeusd/gitty/releases/download/v0.1.0/gitty_0.1.0_darwin_amd64.tar.gz"
    sha256 "176335d79708c331eb6aff616cae836637fd4b89c445a227b84b97492e5ea631"

    define_method(:install) do
      bin.install "gitty"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/wiremeusd/gitty/releases/download/v0.1.0/gitty_0.1.0_darwin_arm64.tar.gz"
    sha256 "7701a2a559765ed4287aaa25e28518ea6646f070107147060be3c53778e497ca"

    define_method(:install) do
      bin.install "gitty"
    end
  end

  test do
    system "#{bin}/gitty --version"
  end
end
