# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitty < Formula
  desc "Interactive GitHub repo cloning from the terminal"
  homepage "https://github.com/wiremeusd/gitty"
  version "0.1.0"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/wiremeusd/gitty/releases/download/v0.1.0/gitty_0.1.0_darwin_amd64.tar.gz"
    sha256 "eccb47ffae95110f60fc8c81fe6963dce7f1fb8d5da3bbe2c13d302d69ddbe1c"

    define_method(:install) do
      bin.install "gitty"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/wiremeusd/gitty/releases/download/v0.1.0/gitty_0.1.0_darwin_arm64.tar.gz"
    sha256 "20a69633d1cf3632573118e8641c86b163fbe33bf29ec2fb521353d18e73490f"

    define_method(:install) do
      bin.install "gitty"
    end
  end

  test do
    system "#{bin}/gitty --version"
  end
end
